### ISSUE TITLE
Panic on special char (non-ASCII ?)

### ISSUE THREAD

**Issue by remche** [soywod/himalaya#104]
himalaya sometimes panicks when a mail subject contains an "é". But it won't when redirecting std or error output to a file. :astonished: 
Seems like it's related to terminal (kitty there) and window size.

[trace.txt](https://github.com/soywod/himalaya/files/6313539/trace.txt)

**Comment by soywod** [comment]
I don't think it is related to the term or to the fact to have é inside the subject. I am also on kitty and I have a é in my name, I would have seen this error during my tests :laugh:. I think it is related to your mail (bad encoding?). Could you share at least the header of your mail? Anyway, the program should not panic, I will investigate.

**Comment by soywod** [comment]
If you add the `--output json`, does the program panic also?

**Comment by paolobarbolini** [comment]
> I don't think it is related to the term or to the fact to have é inside the subject. I am also on kitty and I have a é in my name, I would have seen this error during my tests :smile: 

The error seems to indicate that you're slicing in the middle of a char boundary. For example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4bf5897cdc2ec5ba0dfdb937b4c17bb2

**Comment by remche** [comment]
I also sometime get `thread 'main' panicked at 'attempted to index str up to maximum usize', src/table.rs:65:41`. Seems related to terminal window size...

> If you add the `--output json`, does the program panic also?

No.

**Comment by soywod** [comment]
I think I see where it could panic (thanks to @paolobarbolini's comment):

https://github.com/soywod/himalaya/blob/f6e70a63d45538f21a548a5250c71a5c61ba174c/src/table.rs#L65

It seems that you are unlucky enough to get a `é` just before the ellipsis :laughing:. It explains also why you don't have this panic with the JSON output. The problem is related to the table.

This part of the code misses tests, I think it's a good moment to solidify it. Or to replace it with a real table builder, maybe sth like https://github.com/phsym/prettytable-rs. Feel free to propose.

**Comment by soywod** [comment]
I did not find a good maintained lib for building table, so I refactored mine. I added tests also, so I can start https://github.com/soywod/himalaya/issues/81 very soon. The error should not appear anymore, since I do not slice in the middle of the string anymore. I added tests with emojis cut at the end, everything seems to work well. Feel free to reopen if you find some strange behaviour.

https://github.com/soywod/himalaya/blob/cddb7bde374f2bcce1ce6e5c812f2fc2b811e124/src/table.rs#L320-L343
