### ISSUE TITLE
Customize table columns + adjust the JSON output

### ISSUE THREAD

**Issue by luckman212** [soywod/himalaya#140]
Wonderful project!

I got it working pretty easily with my Fastmail account.

I'd like to use this to run some analysis based on specific message headers. Is it possible to output (either in `plain` or `JSON`) specific headers?

something like

```
himalaya --output json --headers Subject,Message-ID,Date
```

**Comment by soywod** [comment]
The only way to do this right now is to use the `--raw` arg of the `read`
command, and then grep headers you are intersted in. Which is horrible. It
could be a good feature tho! I keep in mind for after the `v1.0.0`. Thanks for
your feedback!

>Wonderful project!
>
>I got it working pretty easily with my Fastmail account.
>
>I'd like to use this to run some analysis based on specific message headers. Is it possible to output (either in `plain` or `JSON`) specific headers?
>
>something like
>
>```
>himalaya --output json --headers uid,subject,message-id
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/soywod/himalaya/issues/140
>

--
Cordialement
Clément DOUIN
Développeur Full Stack
+33 6 30 34 35 47
https://soywod.me

**Comment by luckman212** [comment]
Thank you for considering it!

**Comment by soywod** [comment]
In fact, this issue can be split in two:

- with the `list` command: shows specific columns (headers) in the table and in the JSON output
- with the `read` command: shows specific headers at the top of the message and in the JSON output (in a `headers` prop)

**Comment by andybrice** [comment]
How do you think the interface should work for this? My first proposal is something like the following, based on [RFC 5322](https://datatracker.ietf.org/doc/html/rfc5322), [The imap-proto Envelope struct](https://github.com/djc/tokio-imap/blob/f6c618d4933c1cd39baf13340328b94b10744df0/imap-proto/src/types.rs#L593-L611), and the [Himalaya Envelope struct](https://github.com/soywod/himalaya/blob/84659587165417a669c6b394dc1915a8ef858e3f/src/domain/msg/envelope_entity.rs#L12-L34):

```shell
himalaya list --fields Subject,Sender,Date
```

It would return each [field body](https://datatracker.ietf.org/doc/html/rfc5322#section-2.2) with minimal data transformation. But further transformations could be specified with a character which is not used in [field name](https://datatracker.ietf.org/doc/html/rfc5322#section-2.2)s. Possibly the colon `:` (unless that causes problems in shell commands). For example:

```shell
himalaya list --fields Subject,Sender:name,Sender:address,Date
```

In theory, this interface could be used to return any [header field](https://datatracker.ietf.org/doc/html/rfc5322#section-2.2), including custom fields.

Fields which have no corresponding header field could be specified using the same character. For example:

```shell
himalaya list --fields Subject,Sender,:flags,Date
```

**Comment by andybrice** [comment]
My second proposal is something like this…

Fields are specified using Himalaya's standard naming scheme and data transformations:

```shell
himalaya list --fields id,flags,subject,sender,date
```

And more advanced header fields (with minimal data transformation) can be specified using quotes:

```shell
himalaya list --fields id,flags,subject,sender,"X-Spam-Status","X-Spam-Level",date
```

Now I look at it, this proposal is probably all-round better than the first one. More conventional and intuitive syntax. More flexible. More continuity with how Himalaya already functions. Just as extensible. And simpler to implement.

**Comment by soywod** [comment]
I think I also prefer the second version for the same reasons. How you would get the sender's name or sender's email with this second version?

**Comment by andybrice** [comment]
> How you would get the sender's name or sender's email with this second version?

I think probably just by adding `sender_name` and `sender_address` properties into Himalaya's Envelope struct.\
So the syntax would be like:

```shell
himalaya list --fields id,flags,subject,sender_name,sender_address,date
```

Maybe the `:` data transform syntax could also be added, allowing things like:

```shell
himalaya list --fields sender:name,"Originator-Return-Address":name
```
Though perhaps I'm getting ahead of myself into feature-creep there.

**Comment by soywod** [comment]
I like this idea of adding special suffix starting by `:` to select a subpart of a value. For example, everything that carries addresses can have a `:name` and `:email` prefix. Or everything related to content type can have a `:subtype` etc. I find this quite flexible and we can iterate easily over time (adding more suffixes). What do you think?

**Comment by andybrice** [comment]
Yes, it would certainly add a lot more flexibility and expansibility. So I guess it is worth the extra upfront work.

And in fact, since the RFC 5322 header names would all be quoted with this syntax, I suppose the special character could simply be dot `.` like so:
```shell
himalaya list --fields sender.name,sender.address,"Originator-Return-Address".raw
```
That would be a more conventional and intuitive syntax, following the "Principle of Least Surprise". And less likely to cause confusion and bugs in shell commands.

**Comment by andybrice** [comment]
And I suppose spaces and parentheses should also be optional for readability?

```shell
himalaya list --fields (sender.name, sender.address, "Originator-Return-Address".raw)
```

**Comment by soywod** [comment]
Totally agreed for the dot, it matches way better than colon. What did you have in mind for the `.raw`? I think it should be the default behaviour (no .something = raw value).

For space and parenthesis I agrees less, plus it depends on the `clap` lib we use for building the CLI, see their default behaviour https://docs.rs/clap/latest/clap/builder/struct.Arg.html#method.multiple_values.

**Comment by andybrice** [comment]
I was intending `.raw` to mean _"literally just a string with no parsing or formatting into higher-level data-structures"_.

Though what with [RFC 1342](https://datatracker.ietf.org/doc/html/rfc1342), it might be more predictable to have something like `.ascii` and `.utf8`. For example:
`subject.ascii` → `=?utf-8?B?R3Jvw59yw6RzY2hlbg==?=`
`subject.utf8` → `Großräschen`

I'd say the default behaviour (with no `.something` suffix) should be as it is currently: Your judgment as developer about how best to parse and format the field data for the given `--output` option. Because many users will likely want to do something simple like `himalaya list --fields date,sender,subject` without having to learn and type a lot of extra syntax.

**Comment by soywod** [comment]
I see, it makes sense. Let's go for it! How long you think it would take you? It is just to get an estimation of how much you could get from the donation Himalaya will receive. I can discuss this by email if you prefer!

**Comment by andybrice** [comment]
> How long you think it would take you?

Ask me again in a few days! The answer will depend entirely on how I get along with Rust.

**Comment by andybrice** [comment]
I've encountered a (possibly insurmountable) problem with the `" "` quotes syntax…

Apparently shells parse quotation marks themselves, before sending the arguments to the CLI. So the CLI can never know whether quotation marks were included in the arguments.

So `lorem --ipsum dolor,"sit",amet` just gets called as: `lorem --ipsum dolor,sit,amet`

So I think we're forced to devise an alternative option. Here are my suggestions…

### 1. Case Sensitive

According to [RFC 5322](https://datatracker.ietf.org/doc/html/rfc5322), a header field name can technically contain any ASCII character except `:`. However, by convention, it appears to me that they always follow the pattern `/^[A-Z][A-Z|a-z|0-9|-]$/` Starting with a capital [A-Z], and then containing only Roman characters, numbers, and hyphens. And also by convention, custom headers always start with "X-".

We could assume these conventions, and simply use case-sensititivity if we need to distinguish between Himalaya's envelope `sender` field and the standard header field `Sender`. Also assuming that header field names will not contain `.` and instead parsing it as the "method call" character.

This is slightly risky though. I can foresee it breaking down on edge-cases with custom headers.

### 2. Colon Syntax

We could use the first syntax I proposed.
```shell
himalaya list --fields :flags,:sender:name,Originator-Return-Address:name,X-Spam-Score,:date
```
It's not pretty. But it would be robust in all possible edge cases.

#### 2a. Alternative Colon Syntax

For neatness, terseness, and simplicity-first, a preceding colon could be used to specify a header rather than a specifying Himalaya field.
```shell
himalaya list --fields flags,sender:name,:Originator-Return-Address:name,:X-Spam-Score,date
```

This perhaps sacrifices the logical consistency of `:` being a property or method accessor. That could be retained with something like:

```shell
himalaya list --fields flags,sender:name,h:Originator-Return-Address:name,h:X-Spam-Score,date
```

### 3. Alternative Delimiter

Instead of `" "` quotes, we could use an alternative delimiter. `' '`, `` ` ` ``, `( )`, `[ ]`, and `< >` all appear to be impossible for the same reason that they get pre-parsed by the shell. So it would probably have to be `{ }` like so:

```list
himalaya list --fields flags,sender.name,{Originator-Return-Address}.name,{X-Spam-Score},date
```
This seems to work fine in ZSH and BASH. Though I worry that `{ }` will be parsed as special characters in some shells, and some programming languages' string literals.

**Comment by soywod** [comment]
> Apparently shells parse quotation marks themselves, before sending the arguments to the CLI. So the CLI can never know whether quotation marks were included in the arguments.

But wait, it does not work with the backslash?

I'm not sure to understand the problem, why not keeping your initial proposition with the dot?

**Comment by andybrice** [comment]
> it does not work when escaping quotes with backslashes?

In theory, yes. Although then the syntax would become:
```shell
himalaya list --fields flags,sender.name,\"X-Spam-Score\",\"Originator-Return-Address\".name,date
```
Which I'd say is very confusing and unpleasant to read and type. When the rest of your CLI is very neat and user-friendly.

> why not keeping your initial proposition with the dot?

The dot syntax would probably be fine. The only problem is: In theory, custom header field names can contain `.` So there would be ambiguity when parsing. Whereas `:` is the delimiter for header field names, so it's an unambiguous grammar. Also `,` `:` is easier to distinguish from `,` `.` visually.

Although, in practice: It appears to me that header field names never contain `.` and none of them clash with Himalaya's identifiers.

So I think this syntax would actually work just fine:
```shell
himalaya list --fields flags,sender.name,Originator-Return-Address.name,X-Spam-Score,date
```

Then we always have the option of allowing `\" \"` or `{ }` for those (probably non-existent) edge-cases where a custom header field name contains `.` or clashes with Himalaya's identifiers.

I've learned [clap-rs](https://github.com/clap-rs/clap) now. So I think I can implement any of these.

**Comment by soywod** [comment]
> The dot syntax would probably be fine. The only problem is: In theory, custom header field names can contain `.` So there would be ambiguity when parsing. Whereas `:` is an unambiguous grammar because it's the delimiter for header field names. Also `,` `:` is easier to distinguish from `,` `.` visually.

Do you think we could customize this? Like adding a setting to change this character (default would be the dot `.`, since it is really not so common to see a dot in a header and it does not collide with Himalaya's identifiers as you said).

**Comment by soywod** [comment]
I gather all Himalaya issues to the same [bug tracker](https://todo.sr.ht/~soywod/himalaya), so I transfer your issue [here](https://todo.sr.ht/~soywod/himalaya/21).
