### ISSUE TITLE
Cache sessions in a daemon

### ISSUE THREAD

**Issue by hardselius** [soywod/himalaya#156]
First of all, this is a fantastic project! I've been toying around with it for a few days.

I use `pass` to store my passwords and I immediately noticed that it introduces a significant delay when used as a password command. It would be great to have the option to cache credentials between executions for when calculating credentials is slow.

**Comment by soywod** [comment]
It is really strange because I also use `pass` as password command and I do not have any delay. Could it be related to your configuration (pass, gpg)?

> It would be great to have the option to cache credentials between executions for when calculating credentials is slow

In a more generic way, I was thinking about adding an option to spawn a daemon that connects to your IMAP server and to wait for commands from the CLI. This way we keep all the login process in memory. But it is clearly not a priority, I will keep this issue for after the `v1.0.0`. Thanks for your feedback!

**Comment by hardselius** [comment]
Peculiar. I'm using a Yubikey, so that might be what's causing the delay. I will have to investigate. 

The daemon sound like a nice addition though.

**Comment by soywod** [comment]
Now that himalaya supports Maildir and Notmuch, I'm not so sure about such daemon. Plus the amount of work is giant compare to the benefits. The only place I still see the feature is in the TUI, but even there we don't need a *daemon*, we can just keep in memory the session while the process runs.
