### ISSUE TITLE
IMAP server error (himalaya command)

### ISSUE THREAD

**Issue by daniellaera** [soywod/himalaya#175]
my config in  ~/.config/himalaya/config.toml

```
name = "my name"
downloads-dir = "/Users/name/Downloads"
signature = """
--
Regards,
"""

[gmail]
default = true
email = "myemail@gmail.com"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "myemail@gmail.com"
imap-passwd-cmd = "mypassword"

smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "myemail@gmail.com"
smtp-passwd-cmd = "mypassword"
```

and I'm still getting this error in the teminal

Could not login to IMAP server
 ↳ No Response: Empty username or password. j5mb120609005wru

what am I missing?

**Comment by toastal** [comment]
What application is called `mypassword`?

**Comment by daniellaera** [comment]
Shoudn’t I have to put my gmail password? in the filed `mypassword`?

**Comment by soywod** [comment]
I invite you to read [the wiki](https://github.com/soywod/himalaya/wiki/Configuration:config-file#global-settings):

> `notify-cmd`: shell command used to notify user when receiving a new message [string]

Also [this](https://github.com/soywod/himalaya/wiki/Troubleshooting:gmail-credentials) could help you if you have trouble with Gmail. Let us know.

**Comment by daniellaera** [comment]
thanks a lot

**Comment by holms** [comment]
@soywod I actually totally don't understand the purpose of this parameter. At least provide tools to use for this param.. where do I store my password? I have no idea how to configure this software with my gmail.

**Comment by soywod** [comment]
> I actually totally don't understand the purpose of this parameter.

As I already explained in the thread, it is for security purpose. It is not safe to store your password as a clear string in a config file. If you want so badly do it, you can write `imap-passwd-cmd = "echo your-password"`. 

> At least provide tools to use for this param..

This is not the role of the tool and it does not fit the Unix philosophy. It exists plenty of tools to manage passwords in CLI. Anyway, I planned to update the doc and add more examples, it will be a good occasion to show different example with different password manager.

> I have no idea how to configure this software with my gmail.

New examples will come in the doc, I will let you know when it is ready!

**Comment by holms** [comment]
* As for unix philosophy there are ENV VARS. Which are perfectly fits with unix philosophy when you use them :) 
* CLI password vaults are real pain, been using it for a while then I've dropped it. Backing up database, then version changes, old db doesn't work. Integrating this with bitwarden or similar might be nice to have, but this probably a really far away future to request.
* Regarding gmail... I've had a huge problem to set it up for 3rd party app. Google changing their dash a lot, I couldn't find how to add password for 3rd party app (I don't have such option at all), but I've managed  to find an option which enables any 3rd party to login with a simple acc password.
* And for the offtopic: I really thought that TUI will be  available within this app. Managing mails purely from cli without tui is real pain, so pardon my irritation, I went to a wrong garden.. Couldn't find how to render html, even when specifying mime, or by using vim plugin, it just shows html tags. I believe your use case for developing this tool might be to use it with vim, but even there I've got such a lag that it's barely usable. This would require  5 separate QA tickets, so don't mind me, won't bother you anymore.

**Comment by soywod** [comment]
> * CLI password vaults are real pain

I am personally using [pass](https://www.passwordstore.org/) for years and I am very happy with.

> * Regarding gmail... I've had a huge problem to set it up for 3rd party app. Google changing their dash a lot, I couldn't find how to add password for 3rd party app (I don't have such option at all), but I've managed  to find an option which enables any 3rd party to login with a simple acc password.

Yeah, it is really hard to keep up to date with their changes. That's why I plan to create different sections in the wiki about how to configure Himalaya with the main providers.

> * I really thought that TUI will be  available within this app

Nop, there is an open issue for that. A TUI is planed but not for now, I prefer first to have a fully functional lib before investing time in interfaces.

> * Managing mails purely from cli without tui is real pain, so pardon my irritation, I went to a wrong garden..

No need to be sorry, this project is very young and is not ready for production usage yet. Just need to be patient ;)

> * Couldn't find how to render html, even when specifying mime, or by using vim plugin, it just shows html tags. I believe your use case for developing this tool might be to use it with vim, but even there I've got such a lag that it's barely usable. This would require 5 separate QA tickets, so don't mind me, won't bother you anymore.

You do not bother me :rofl: Issues are made for it, please feel free to open them. As I said, this project is really young and experimental. If you are just looking for a production-ready TUI then see alternative tools like aerc, mutt, neomutt, meli etc. With Himalaya I try to extract a Rust lib for managing emails, this way you can build any kind of client at the top of it. But I need time to make it production-ready. Once this stage reached, I will be able to focus on UIs!

**Comment by toastal** [comment]
A *lot* of applications use a password command (most CLI email, `mbsync`, `vdirsync`, `senpai`, `matterhorn`, etc.). I think it's pretty intuitive and switching to `pass` I now have it synced to other devices via `git`.


I wish the best advice would be to suggest that for your personal privacy, just don't use GMail, but literally all employers and contracts I've taken in the last 7 years have exclusively GSuite so if you want a tool that is for work and your actual private mail, you still have to support the goliath G. Google has not been making this any easier on *any* project though.

The Neovim plugin *can* act like a TUI, but it can be a bit cumbersome to use versus a TUI that opens Neovim to write mail because the controls are built to edit text more than navigate menus. But you can, as noted in the docs, run `nvim +Himalaya` if you need something TUI-like.
