### ISSUE TITLE
Change order when listing

### ISSUE THREAD

**Issue by palb91** [soywod/himalaya#279]
What do you think about an option to change the default order when listing?
It could be done in two flags, `-o, --order-by` to choose the column to sort, and `-r, --reverse` to… euh… reverse the order.

**Comment by palb91** [comment]
Related to #265, because I also have the same behavior than @codeinred, where the oldest mails are listed first.
I think that it appends after running `mbsync`. If I don't use it, new mails appears first, after a call to mbsync the ID order changes.
I really appreciate your tool, I'm in the process to replace my setup `mbsync`+`notmuch` with `himalaya` only. Thanks @soywod!

**Comment by soywod** [comment]
> Related to #265, because I also have the same behavior than @codeinred, where the oldest mails are listed first.

The problem is that the sequence number does not match the date. In a regular set up, a small sequence number = an old message. I'm afraid there is not that much I can do :disappointed:. I thought about reordering messages from the rust side (instead of IMAP), but we will still not get the right messages. The best we can do is either to check if there is an option in `mbsync` to reverse the default order, or to wait for https://github.com/soywod/himalaya/issues/34.

> It could be done in two flags, `-o, --order-by` to choose the column to sort, and `-r, --reverse`

I plan to add them with #34 :slightly_smiling_face:
