### ISSUE TITLE
Customizable query for `himalaya notify`

### ISSUE THREAD

**Issue by gleachkr** [soywod/himalaya#289]
It would be helpful for `himalaya notify` to be able to query for emails that are, e.g. `not seen` rather than `new`, since in some (tragic) situations the `\Recent` flag might not be set on incoming email.

**Comment by soywod** [comment]
I add a new config option `notify-query` which takes a valid IMAP query string (the same as the `query` command, see https://tools.ietf.org/html/rfc3501#section-6.4.4). It will be shipped with the next release, stay tuned!

**Comment by sbromberger** [comment]
Could the wiki be updated with examples of how to use this and `himalaya watch`? I'm not getting notifications but I'm probably not doing things correctly. (I have `watch-cmds = ["echo Mailbox change"]` as a test and I guess I expected "Mailbox change" to be echoed whenever something happens, but... nothing.)

**Comment by soywod** [comment]
The wiki has been updated with the new release I just published: https://github.com/soywod/himalaya/wiki/Configuration:config-file. About the `watch-cmds`, I'm not surprise that you see nothing, because commands are run in a separated thread. Do you have the `libnotify` installed? You can try sth like `watch-cmds = ["notify-send subject body"]`.

**Comment by sbromberger** [comment]
No libnotify - it requires over 500 dependencies and I'm keeping my system minimal.

**Comment by soywod** [comment]
I see. Maybe you can try to create a script shell that writes sth in a file, sth like:

```sh
#!/bin/bash

echo test >/tmp/test
```

and set up `watch-cmds = ["your-script.sh"]`

**Comment by davidhaley** [comment]
Example for others:

`notify-query = "not seen"`
