### ISSUE TITLE
Unread flag not showing properly

### ISSUE THREAD

**Issue by piotryordanov** [soywod/himalaya#360]
Any idea why the unread flag is showing as a box on my terminal (alacritty, fish, wsl2) and neovim?

![image](https://user-images.githubusercontent.com/48773775/162543905-39f8229e-f736-482b-a376-4f675b057928.png)
![image](https://user-images.githubusercontent.com/48773775/162543920-3eac9d0e-f878-44b9-907b-2b5ffecf1b16.png)

**Comment by soywod** [comment]
> Any idea why the unread flag is showing as a box on my terminal
> (alacritty, fish, wsl2) and neovim?

It looks like your terminal does not handle well emoji. This is the
[unicode] used by himalaya. I will close the issue since it is not
directly related to the Himalaya, but feel free to continue the
discussion below. Try to change your main terminal font (one that handle
better unicodes)?

[unicode]: https://emojipedia.org/unicode-black-flag/

**Comment by piotryordanov** [comment]
Alright no worries. Thx regardless :)
