### ISSUE TITLE
Show if mail has an attachment in list command

### ISSUE THREAD

**Issue by omani** [soywod/himalaya#403]
hi,
I have no way of figuring out if a mail has an attachment. (though I could parse all header files, but who wants that?).

can we provide a flag or some sort to show if a message has an attachment in `himalaya` or `himalaya list` respectively?

I see #16 regarding this. but Im not sure. my flags are still empty.
v0.5.10 here.

thanks.

**Comment by soywod** [comment]
> I see #16 regarding this. but Im not sure. my flags are still empty.

Yes, it was one of the first feature I implemented, but the code changed so much since and this feature was removed because of perf issues. The `list` command lists only the envelopes of emails: it is faster, but there is no information about attachments. Maybe I can propose to introduce a new flag (sth like `himalaya list --full`) that could fetch emails instead of envelopes, and so we could show information about attachments. What do you think?

**Comment by omani** [comment]
yes. I guess there is no way around scripting it anyway. so a `--full` would make things easier here if it does that job for us.

looking forward to seeing this feature implemented soon.

**Comment by soywod** [comment]
I gather all Himalaya issues to the same [bug tracker](https://todo.sr.ht/~soywod/himalaya), so I transfer your issue [here](https://todo.sr.ht/~soywod/himalaya/8).
