### ISSUE TITLE
Truncate sender name when listing messages

### ISSUE THREAD

**Issue by zanona** [soywod/himalaya#434]
I believe that, as the message subject field gets truncated on small viewports, perhaps the same could be applied to the sender name, to help to prevent breaking the column layout a little?

![](https://user-images.githubusercontent.com/32017/209089315-c1a1f173-ebc1-471f-9dd1-c6d7f8fbe643.png)

**Comment by soywod** [comment]
Nice email address :smile: indeed, a long sender breaks the layout because only one column can shrink at a time. I need to adjust to code to be able to shrink more than one column. Thank you for reporting the bug!

---

I am moving away from GitHub issues, so I reopened your issue on the new bug tracker at https://todo.sr.ht/~soywod/himalaya/28. The GitHub issues panel will be closed with the next release #433.
