### ISSUE TITLE
IMAP `CLOSE` and `CHECK` command being invoked when no mailbox is selected

### ISSUE THREAD

**Issue by titanism** [soywod/himalaya#458]
Per my findings with WildDuck, it appears that `himalaya account sync` is calling `CLOSE` and `CHECK` when no mailbox is selected.  Not sure if this is just a WildDuck issue, but I don't think it should be trying to invoke these commands if no mailbox is selected.

Ref:
- https://github.com/nodemailer/wildduck/issues/556
- https://github.com/nodemailer/wildduck/issues/558

**Comment by soywod** [comment]
> It appears that `himalaya account sync` is calling `CLOSE` and `CHECK`
> when no mailbox is selected.

Actually we are using the `imap` crate, and the public API does not
expose clearly the state of a mailbox. I recently discussed about it
with the author of <https://github.com/duesee/imap-flow>, and he plans
to design a better API. Since we plan to migrate from `imap` to
`imap-flow`, this issue should disappear by itself!

**Comment by soywod** [comment]
I close the issue, as it should resolve by itself the day we migrate to `imap-flow`.
