### ISSUE TITLE
Migration to SourceHut

### ISSUE THREAD

**Issue by polarathene** [soywod/himalaya#465]
It might be good to have a pinned issue, or one that the README / issue template below points to regarding the motivation to move away from Github to SourceHut? Will the Github repo here lock issues and archive? Or will it still actively mirror the SourceHut repo?

I'm additionally raising an issue about the docs site being down (`pimalaya.org`), something that wouldn't be an issue if they were hosted via Github Pages?

I'm not familiar with SourceHut, nor do I have any motivation to create an account there presently, hopefully it's worthwhile for you. I've seen similar migrations to GitLab before, but as a user that was not something I could actively participate in as a basic feature for viewing / tracking notifications across projects had been a known issue and unresolved for years (possibly still the case), you'd only have email notifications available.

**EDIT:** Just looked at the [new home](https://sr.ht/~soywod/pimalaya/) (_and the recent DDoS issues blogged about from this service in Jan 2023_), and I am having a difficult time understanding why you're ditching Github for it. I definitely think it'll add friction towards users contributing PRs and participating / reporting issues 🤷‍♂️ (_and perhaps discovery somewhat, I came across the project from Github Topics_)

---

<details>
<summary>Original issue template discouraging opening issues on GH</summary>

Himalaya is slowly migrating away from GitHub. The new bug tracker is
now on [sourcehut](https://sr.ht/). You can submit an issue either by:

* Sending an email at
  [~soywod/pimalaya@todo.sr.ht](mailto:~soywod/pimalaya@todo.sr.ht)
  (it is the simplest since you do not need to create any account)
* Submitting [this form](https://todo.sr.ht/~soywod/pimalaya) (you
  need a free sourcehut account)

</details>

**Comment by prmadev** [comment]
To be honest, one of the main attractions of pimalaya project was that it was, mostly, hosted on sourcehut. 
True, sourcehut used a workflow that is unfamiliar to most developers. But the workflow is mostly the one that git is made for, exceptionally decentralized and has much less friction, once you learn it.
Also your progress is not bound to a particulat provider. When sr.ht is down, I still have my email's mailbox. 

Of course there are always instability problems when working with smaller services. And a nasty one of them is vulnerability to huge and advanced attacks like a layer 3 DDoS attack. 
But is also the benefit that thr smaller service has to be more customer oriented than the default option. 

Now, if we consider things like codeberg  and gitlab, yes, the move suggests that the contributers should sign up for the new service, which is probably not something that most people are willing to do. 
But to contribute to a repo hosted on sr.ht, a contributer should only be willing to send an email to some address, using built-in commands of git. 
And even when sr.ht email services where down, you could send email to those addresses, they just get delivered when the service is up. 
For example, see this patch that I sent when the whole of sourcehut was down:
https://lists.sr.ht/~soywod/pimalaya/patches/48533
It still managed to reach the intended endpoint, when ever. 
So these attacks don't hurt as much as it might for other source forges. 
Another benefit is that while github is leaving accessibility behind everyday, sourcehut is pushing extremely hard on the boundries of html only. 
You might not care about this one but Microsoft and the enshitifications that follows it, is not a good news either, nor is them doubling down on AI instead of advancing the git workflow itself. 

And to be honest for a product centered around emails on the command line, an email centric workflow that git is more equipt to handle makes much more sense to me.
So to me, as a new contributer, I felt much more welcome using sourcehut; Even though I regularly have to use github and gitlab for my work. 

But hey, I was already sold on sourcehut. And I'm pretty new to project. So what do I know? 😊

**Comment by polarathene** [comment]
> So to me, as a new contributer, I felt much more welcome using sourcehut; Even though I regularly have to use github and gitlab for my work.
> 
> But hey, I was already sold on sourcehut. And I'm pretty new to project. So what do I know? 😊

Cheers for sharing your perspective :)

---

> Another benefit is that while github is leaving accessibility behind everyday, sourcehut is pushing extremely hard on the boundries of html only.

I guess this depends on different a11y needs for the target audiences. For me the UX is a big step downwards at a glance. I don't know how the support for an alternative Github Actions is like there, or the review process that I very much like and use other features Github provides (_I have no interest in the AI stuff_).

SourceHut reminds me of mailing lists, and browsing git repos with a [minimal web client like the kernel hosts](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git), with a mix of bugzilla-esque frontend? I just don't see that working with my workflows. I happily use many terminal tabs and CLI programs, but I don't shunt GUI apps away when they serve me better either 😅 

---

If the project continues to thrive, that's fantastic and I hope SourceHut is worthwhile to migrate to for the project.

Considering user feedback on UX I've seen on other projects like KDE with Bugzilla (_they only in recent years moved to Gitlab IIRC, can't recall if they migrated from Bugzilla yet for user bug reports however_) and some Gitlab ones to some degree. There are some loss in contributions/reports.

All the best with it though! 🚀

**Comment by soywod** [comment]
> It might be good to have a pinned issue, or one that the README / issue template below points to regarding the motivation to move away from Github to SourceHut?

It is a very good idea, I will do it ASAP.

> Will the Github repo here lock issues and archive?

I would like to lock issues, but then you loose access to the history. So I instead leave it open with a template. I may lock it once we reach the `v1`. Regarding the archive, it will not happen for the 2 following reasons:

- Multi-platform pre-built releases: GitHub Actions is required to build releases on Linux, MacOS and Windows (not possible on sourcehut).
- Visibility and discovery: I cannot deny the benefit of using GitHub for the visibility of the project, and it helps people to discover it.

So the logic is the following: everything is hosted on sourcehut by default except stuff (mostly interfaces) requiring multi-platform releases. In this case we use GitHub for git, CI (actions) and releases. 

> For me the UX is a big step downwards at a glance.

I come from the web world, and I agree with you. It is not the same approach: sourcehut is really minimalistic, it is not really made to be used everyday in your workflow (like GitHub does), instead you use emails (as @prmadev explained). It is definitely sth that needs to be better explained on the README!

**Comment by soywod** [comment]
I would also add that Himalaya CLI fits well the git email workflow, as you can use Himalaya CLI itself to send patches :smile:

**Comment by polarathene** [comment]
> It is a very good idea, I will do it ASAP.

Cheers! ❤️ 

---

> Visibility and discovery: I cannot deny the benefit of using GitHub for the visibility of the project, and it helps people to discover it.

> So the logic is the following: everything is hosted on sourcehut by default except stuff (mostly interfaces) requiring multi-platform releases. In this case we use GitHub for git, CI (actions) and releases.

Sounds good! 👍

Those are definitely great perks Github offers. I hope with those reasons this repo will still mirror the main repo as a result as browsing source/history in the browser, along with `git blame` and related features I find quite handy :)

While the friction/comfort for some contributors will go up, those that really want to get something fixed or contribute in other ways will go to SourceHut, I know I do for projects when it really matters to me and they don't operate on Github 👍

**Comment by soywod** [comment]
I updated the [README](https://github.com/soywod/himalaya?tab=readme-ov-file#contributing) as well as the [CONTRIBUTING](https://github.com/soywod/himalaya/blob/master/CONTRIBUTING.md) guide, let me know if it is clear enough. Thank you!

**Comment by polarathene** [comment]
> let me know if it is clear enough

I think the guidance looks quite good 👍 

I would still perhaps make the README a bit clearer that Github is a mirror of SourceHut repo (_probably a bit annoying when mirroring though_).

Maybe just pin this issue even though it's closed? That should still keep it visible if you freeze the ability to open / interact with issues I think? Or leave as-is, I'd normally check the latest closed issues too, so this shouldn't be too hard to come across.

**Comment by soywod** [comment]
> I would still perhaps make the README a bit clearer that Github is a
> mirror of SourceHut repo

Well, technically it is not a mirror, the source code is _really_ hosted
on GitHub, but all the rest (mailing list, bug tracking, patches…) are
on sourcehut.

> Maybe just pin this issue even though it's closed? That should still
> keep it visible if you freeze the ability to open / interact with
> issues I think? Or leave as-is, I'd normally check the latest closed
> issues too, so this shouldn't be too hard to come across.

If I disable the issue feature, everything saddly disappears. So I will
pin it as you propose. Thanks!
