### ISSUE TITLE
Allow deleting more than one message

### ISSUE THREAD

**Issue by srid** [soywod/himalaya#85]
`himalaya delete` can allow more than one argument so that an user can delete multiple messages in one go.

Perhaps the same can be done in other commands, that accept a single message ID as an argument. Though if they accept other *kinds* of arguments as well (eg: `himalaya flag add`), that wouldn't be possible  ... unless we compromise on CLI simplicity to do something tricky, like supporting comma-separated list of IDs, but that's probably not worth considering unless there is a way to batch these operations in a single IMAP request for performance (compared to what you can achieve with `xargs -n 1`).

**Comment by soywod** [comment]
I theory it's already the case. Most of the IMAP commands accept a sequence of UID, as defined in the [RFC](https://tools.ietf.org/html/rfc3501#section-9):

> sequence-set    = (seq-number / seq-range) *("," sequence-set)

Maybe some adjustment will be needed. I will check the compatibility as soon as I can.

**Comment by soywod** [comment]
Yes I confirm that it works *at least* for the `delete` command. You just need to pass a valid sequence set as defined in the RFC:

- `1,2,5,7` for a basic sequence
- `1:10` for a range
- `10:*` for a bigger range (the `*` may need to be escaped, otherwise the term could interpret as a glob)

It also works for the `flag` commands and subcommands, but it does not for all the rest. I think we can leave like this. I am afraid to make the CLI too complex. Maybe it is sth we can discuss again after the v1.0.0?

**Comment by srid** [comment]
Ah, I didn't know about this syntax. Which RFC are you referring to?

**Comment by srid** [comment]
This looks good enough, actually. Perhaps it should be documented. At least the help text should make it clear that arbitrary number of messages (per the IMAP spec) can be specified. Currently it gives the impression that only one ID can given,

```
ARGS:
    <UID>    Specifies the targetted message
```

**Comment by soywod** [comment]
Yes indeed. This was not planned at all, I did not expect this behaviour :laughing:. The problem is that I use a common function:
https://github.com/soywod/himalaya/blob/0907683e314fa2d29fdead2b566c2522d4c4ad06/src/msg/cli.rs#L29-L34

So I need to split the function in two (or to pass the desc by parameter). After all, most of the users will never know about this, maybe I could just add an entry in the wiki for the `flag` and `delete` commands?

**Comment by soywod** [comment]
I added examples in the wiki for the delete commands: https://github.com/soywod/himalaya/wiki/Usage:msg:delete.
