### ISSUE TITLE
Copy/move/delete a msg

### ISSUE THREAD

**Issue by srid** [soywod/himalaya#95]
Being able to delete a message (`gd` keybinding?) from the message list would be a useful function in the Vim plugin.

**Comment by soywod** [comment]
Yes I didn't have time to implement it yet (like the copy and move commands). Thanks for pointing it out!

**Comment by soywod** [comment]
Added in the [v0.3.2](https://github.com/soywod/himalaya/releases/tag/v0.3.2) :tada: 

Default keybindings are `gC` for copy, `gM` for move and `gD` for delete. Delete accepts visual selection (= delete multiple messages at once).
I set up those keybindings because they seem not so intrusive, but I personally replaced the `gD` with `dd` and `D` (to match more the normal vim behaviour).
